// Equivalent Node.js version of the Java Library Management System
// TEMPLATE SOURCE CODE GENERATED BY CHATGPT AND MODIFIED MANUALLY

// In-memory data store
let output = "";
let currentUser = null; // Store current user
let pendingResolve = null; // For inqueue waiting

async function main(){
    const express = require('express');
    const app = express();
    const PORT = 3000;

    // Middleware
    app.use(express.json());
    app.use(express.static('public'));

    // Initialize the main program and its users at start
    const library = new LibraryProgram();
    await library.InitializeLibrary();
    await library.InitializeUsers();

    // Default Endpoint
    app.get('/', (req, res) => {
      res.redirect('/login');
    });

    // Login endpoint
    app.post('/api/login', (req, res) => {
      const { user, pass } = req.body;
      const username = library.GetUserByUsername(user.trim());
      const password = pass.trim();

      if(username && username.getPassword() === password) {
          res.status(200).json({ success: true, username: currentUser });
          currentUser = user;
          library.SetCurrentUser(user);

          // Notification Check at every login
          let notif = library.hasNotification(username);
          if (notif.length > 0) appendToOutput(notif);

          // Start the Library Function
          library.Start();

        } else {
          res.status(400).json({ error: 'Invalid login' });
        }
    });

    // Get current user endpoint
    app.get('/api/user', (req, res) => {
      if (currentUser) {
        res.json({ name: currentUser });
      } else {
        res.status(404).json({ error: 'No user logged in' });
      }
    });

    // Get all items
    app.get('/api/output', (req, res) => {
      res.json(output);
    });

    app.post('/api/output', (req, res) => {
      const { inputValue } = req.body;
      if (inputValue) {
        if (pendingResolve) {
          pendingResolve(inputValue); // resolve the promise waiting for input
          pendingResolve = null;
        }
        res.status(201).json(output);
      } else {
        res.status(400).json({ error: 'Input is required' });
      }

      output = "";

    });

    app.get('/api/logout', (req, res) => {
          if (currentUser) {
            currentUser = null;
            library.SetCurrentUser(null);
            output = "";
            res.json({ name: currentUser });
          } else {
            res.status(404).json({ error: 'No user logged in' });
          }

    });

    // Start server
    app.listen(PORT, () => {
      console.log(`Basic app running at http://localhost:${PORT}`);
    });
}

function appendToOutput(input) {
  output += input + "\n"; // append the new string
}

function clearOutput(){
  output = ""; // Clear Output
}

function ask() {
  return new Promise(resolve => {
    pendingResolve = resolve;
  });
}

// ---- Date Helpers (replacement for LocalDate) ----
function today() {
    return new Date();
}

function plusDays(date, days) {
    let d = new Date(date);
    d.setDate(d.getDate() + days);
    return d;
}

function formatDate(date) {
    return date.toISOString().split("T")[0];
}



// --------------------------------------------
//                  BOOK CLASS
// --------------------------------------------
class Book {
    constructor(title, author) {
        this.title = title;
        this.author = author;
        this.borrowId = 999;
        this.dueDate = today();
        this.holdList = [];
    }

    getTitle() { return this.title; }
    getAuthor() { return this.author; }
    getBorrowId() { return this.borrowId; }

    setBorrowedId(id) { this.borrowId = id; }

    getDueDate() { return formatDate(this.dueDate); }
    setDueDate(date) { this.dueDate = date; }

    getNextUserHoldList() {
        if (this.holdList.length === 0) return "";
        return this.holdList[0];
    }

    addUserHoldList(username) {
        this.holdList.push(username);
    }

    removeUserHoldList() {
        if (this.holdList.length > 0) {
            this.holdList.shift();
        }
    }

    isCheckedOut() {
        return this.borrowId !== 999;
    }
}

// --------------------------------------------
//                  USER CLASS
// --------------------------------------------
class User {
    constructor(username, password) {
        this.username = username;
        this.password = password;
    }
    getUsername() { return this.username; }
    getPassword() { return this.password; }
}

// --------------------------------------------
//              MAIN LIBRARY CLASS
// --------------------------------------------
class LibraryProgram {

    constructor() {
        this.catalogue = [];
        this.users = [];
        this.currentUser = null;
    }

    InitializeLibrary() {
        const books = [
            ["The Great Gatsby", "F. Scott Fitzgerald"],
            ["To Kill a Mockingbird", "Harper Lee"],
            ["1984", "George Orwell"],
            ["Pride and Prejudice", "Jane Austen"],
            ["The Hobbit", "J.R.R. Tolkien"],
            ["Harry Potter", "J.K. Rowling"],
            ["The Catcher in the Rye", "J.D. Salinger"],
            ["Animal Farm", "George Orwell"],
            ["Lord of the Flies", "William Golding"],
            ["Jane Eyre", "Charlotte Bronte"],
            ["Wuthering Heights", "Emily Bronte"],
            ["Moby Dick", "Herman Melville"],
            ["The Odyssey", "Homer"],
            ["Hamlet", "William Shakespeare"],
            ["War and Peace", "Leo Tolstoy"],
            ["The Divine Comedy", "Dante Alighieri"],
            ["Crime and Punishment", "Fyodor Dostoevsky"],
            ["Don Quixote", "Miguel de Cervantes"],
            ["The Iliad", "Homer"],
            ["Ulysses", "James Joyce"]
        ];

        for (const [title, author] of books) {
            this.AddBook(title, author);
        }
    }

    InitializeUsers() {
        this.AddUser("alice", "pass123");
        this.AddUser("bob", "pass456");
        this.AddUser("charlie", "pass789");
    }

    AddBook(title, author) {
        this.catalogue.push(new Book(title, author));
    }

    GetBook(i) { return this.catalogue[i]; }
    GetCatalogueSize() { return this.catalogue.length; }

    AddUser(username, password) {
        this.users.push(new User(username, password));
    }

    GetUsersSize() { return this.users.length; }

    GetUserByUsername(username) {
        return this.users.find(u => u.username === username) || null;
    }

    GetPasswordByUsername(username) {
            return this.users.find(u => u.username === pass) || null;
        }

    GetUserId(username) {
        return this.users.findIndex(u => u.username === username);
    }

    SetCurrentUser(username) {
        this.currentUser = this.GetUserByUsername(username);
    }

    GetCurrentUser() {
        return this.currentUser;
    }

    GetBookHold(bookId, username) {
        const book = this.GetBook(bookId);

        for (let i = 0; i < book.holdList.length; i++) {
            if (i === 0 &&
                book.holdList[0] === username &&
                book.getBorrowId() === this.GetUserId(username)) {
                return false;
            }
            if (book.holdList[i] === username) return true;
        }

        return false;
    }

    GetUserHold(username) {
        for (let i = 0; i < this.GetCatalogueSize(); i++) {
            if (this.GetBookHold(i, username)) return true;
        }
        return false;
    }

    getBorrowedBooksCount() {
        const id = this.GetUserId(this.currentUser.username);
        return this.catalogue.filter(b => b.borrowId === id).length;
    }

    getAvailableBooksCount() {
        return this.catalogue.filter(b => b.borrowId === 999).length;
    }

    hasNotification(username) {
        let msg = "";
        for (let i = 0; i < this.GetCatalogueSize(); i++) {
            const book = this.GetBook(i);
            if (book.holdList.length > 0 && book.holdList[0] === username) {
                msg += `NOTICE: The book ${book.title} is now available.\n`;
            }
        }
        return msg;
    }

    bookBorrow(bookId, username) {
        const book = this.GetBook(bookId);

        if (book.borrowId === 999 && this.getBorrowedBooksCount() < 3) {
            if (book.holdList.length === 0 || book.holdList[0] === username) {
                book.setBorrowedId(this.GetUserId(username));
                book.setDueDate(plusDays(today(), 14));

                if (!this.GetBookHold(bookId, username)) {
                    book.addUserHoldList(username);
                }
                return true;
            }
        }
        return false;
    }

    bookReturn(bookId, username) {
        const book = this.GetBook(bookId);
        if (book.borrowId === this.GetUserId(username)) {
            book.setBorrowedId(999);
            book.removeUserHoldList();
            return true;
        }
        return false;
    }

    bookHold(bookId, username) {
        if (!this.GetUserHold(username)) {
            this.GetBook(bookId).addUserHoldList(username);
            return true;
        }
        return false;
    }

    async Start() {
        while (true) {
            appendToOutput("----- MAIN MENU -----");
            appendToOutput("1. Borrow a book");
            appendToOutput("2. Return a book");
            appendToOutput("Please enter your selection: ");

            const option = await ask();

            switch (option) {
                case "1":
                    await this.borrowProcess();
                    break;
                case "2":
                    await this.returnProcess();
                    break;
                default:
                    appendToOutput("Invalid Choice. Please Retry.");
            }
        }
    }

    async borrowProcess() {
        appendToOutput("----- BORROWING -----");

        const userId = this.GetUserId(this.currentUser.username);
        const numBorrow = this.getBorrowedBooksCount();

        appendToOutput(`Number of borrowed books: ${numBorrow}`);
        this.displayCollection(userId);

        while (true) {
            appendToOutput("Enter the # of the Book you want to borrow (0 to cancel): ");
            let choice = await ask();
            let inputValue = parseInt(choice);

            if (isNaN(inputValue)) {
                appendToOutput("Invalid input. Enter a number.");
                continue;
            }

            if (inputValue === 0) return;

            if (inputValue >= 1 && inputValue <= 20) {
                let bookIndex = inputValue - 1;
                let book = this.GetBook(bookIndex);

                // identical logic as Java version
                if (book.borrowId !== 999) {
                    appendToOutput("Book borrowing unsuccessful. Someone is borrowing this book.");
                    appendToOutput("Hold this book? (1=Yes, 2=No): ")
                    let hold = await ask();
                    if (hold === "1") {
                        this.bookHold(bookIndex, this.currentUser.username);
                        appendToOutput("Book on hold.");
                    }
                    return;
                }

                if (numBorrow >= 3) {
                    appendToOutput("Limit reached.");
                    appendToOutput("Hold this book? (1=Yes, 2=No): ")
                    let hold = await ask();
                    if (hold === "1") {
                        this.bookHold(bookIndex, this.currentUser.username);
                        appendToOutput("Book on hold.");
                    }
                    return;
                }

                appendToOutput("BOOK INFORMATION:");
                appendToOutput(`${inputValue} | ${book.title} | ${book.author}`);
                appendToOutput(`Expected Return Date: ${formatDate(plusDays(today(), 14))}`);
                appendToOutput("Confirm borrowing? (1=Yes, 2=No): ")
                let confirm = await ask();
                if (confirm === "1") {
                    if (this.bookBorrow(bookIndex, this.currentUser.username)) {
                        appendToOutput("Book successfully borrowed.");
                    } else {
                        appendToOutput("Failed to borrow book.");
                    }
                }
                return;
            }

            appendToOutput("Invalid choice.");
        }
    }

    displayCollection(userId) {
        for (let i = 0; i < this.GetCatalogueSize(); i++) {
            const b = this.GetBook(i);
            let entry = i + 1;

            if (b.borrowId === userId) {
                appendToOutput(`${entry} | ${b.title} | ${b.author} | *Checked Out, Due: ${b.getDueDate()}`);
            } else if (b.borrowId !== 999) {
                appendToOutput(`${entry} | ${b.title} | ${b.author} | Checked Out, Due: ${b.getDueDate()}`);
            } else {
                appendToOutput(`${entry} | ${b.title} | ${b.author} | Available`);
            }
        }
    }

    async returnProcess() {
        appendToOutput("----- RETURNING -----");

        const userId = this.GetUserId(this.currentUser.username);

        appendToOutput("Currently borrowed books:");
        this.displayBorrowedBooks(userId);

        if (this.getBorrowedBooksCount() === 0) {
            appendToOutput("No books to return.");
            return;
        }

        while (true) {

            appendToOutput("Enter # of book to return (0 to cancel): ")
            let choice = await ask();
            let inputValue = parseInt(choice);

            if (inputValue === 0) return;

            if (inputValue >= 1 && inputValue <= 20) {
                let bookIndex = inputValue - 1;

                if (this.GetBook(bookIndex).borrowId === userId) {
                    appendToOutput("Confirm return? (1=Yes, 2=No): ");
                    let confirm = await ask();

                    if (confirm === "1") {
                        this.bookReturn(bookIndex, this.currentUser.username);
                        appendToOutput("Book returned.");
                        return;
                    }
                } else {
                    appendToOutput("Invalid book number.");
                }
            }
        }
    }

    displayBorrowedBooks(userId) {
        for (let i = 0; i < this.GetCatalogueSize(); i++) {
            const b = this.GetBook(i);
            if (b.borrowId === userId) {
                appendToOutput(`${i + 1} | ${b.title} | ${b.author} | Checked Out, Due: ${b.getDueDate()}`);
            }
        }
    }
}

main();


